name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  MD_FOLDER: posts
  DEPLOY_BRANCH: prebuilt
  MARKDOWN_REPO: garden

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SSG repo
        uses: actions/checkout@v6
        with:
          repository: dhzdhd/jade
          path: .

      - name: Checkout main repo
        uses: actions/checkout@v6
        with:
          path: ${{ env.MARKDOWN_REPO }}

      - name: Cleanup SSG repository
        run: |
          rm -rf .config
          rm -rf posts
          mkdir .config
          mkdir posts

      - name: Move config files
        run: mv ${{ env.MARKDOWN_REPO }}/.config/* .config

      - name: Create config.ts if it does not exist
        run: |
          if [ ! -f .config/config.ts ]; then
            touch .config/config.ts
            echo "export default {}" > .config/config.ts
          fi

      - name: Create custom.css if it does not exist
        run: |
          if [ ! -f .config/custom.css ]; then
            touch .config/custom.css
          fi

      - name: Create landing.md if it does not exist
        run: |
          if [ ! -f .config/landing.md ]; then
            touch .config/landing.md
            echo "# Hello World" > .config/landing.md
          fi

      - name: Move markdown files
        run: |
          rsync -avm --include='*/' "./${{ env.MARKDOWN_REPO }}/${{ env.MD_FOLDER }}/" "posts"

      - name: Copy images to static/
        run: |
          rsync -avm --include='*.png' --include='*.jpg' --include='*.jpeg' --include='*.webp' --include='*.svg' --include='*/' --exclude='*' "${{ env.MARKDOWN_REPO }}/${{ env.MD_FOLDER }}/" "static"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: |
          npx playwright install-deps
          npx playwright install

      - name: Install Puppeteer dependencies
        run: npm i puppeteer

      - name: Build project
        run: npm run build

      - name: Push built files to deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ${{ env.DEPLOY_BRANCH }}
          folder: build
