name: Build

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  MD_FOLDER: posts
  DEPLOY_BRANCH: deploy

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v6

      - name: Checkout SSG repo
        uses: actions/checkout@v6
        with:
          repository: dhzdhd/jade
          path: ssg

      - name: Cleanup SSG repository
        run: |
          rm -rf ssg/.config
          rm -rf ssg/posts
          mkdir ssg/.config
          mkdir ssg/posts

      - name: Move config files
        run: mv ./.config/* ./ssg/.config

      - name: Create config.ts if it does not exist
        run: |
          if [ ! -f ssg/.config/config.ts ]; then
            touch ssg/.config/config.ts
            echo "export default {}" > ssg/.config/config.ts
          fi

      - name: Create custom.css if it does not exist
        run: |
          if [ ! -f ssg/.config/custom.css ]; then
            touch ssg/.config/custom.css
          fi

      - name: Create landing.md if it does not exist
        run: |
          if [ ! -f ssg/.config/landing.md ]; then
            touch ssg/.config/landing.md
            echo "# Hello World" > ssg/.config/landing.md
          fi

      - name: Move markdown files
        run: |
          rsync -avm --include='*/' "${{ env.MD_FOLDER }}/" "ssg/posts"

      - name: Copy images to static/
        run: |
          rsync -avm --include='*.png' --include='*.jpg' --include='*.jpeg' --include='*.webp' --include='*.svg' --include='*/' --exclude='*' "${{ env.MD_FOLDER }}/" "ssg/static"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Install Puppeteer dependencies
        run: npm i puppeteer

      - name: Build project
        run: npm run build
